environment:
  matrix:
    - PYTHON: "C:\\Miniconda36"
      PY_VERSION: "3.6"
    - PYTHON: "C:\\Miniconda36-x64"
      PY_VERSION: "3.6"
    - PYTHON: "C:\\Miniconda36"
      PY_VERSION: "3.7"
    - PYTHON: "C:\\Miniconda36-x64"
      PY_VERSION: "3.7"
    - PYTHON: "C:\\Miniconda36"
      PY_VERSION: "3.8"
    - PYTHON: "C:\\Miniconda36-x64"
      PY_VERSION: "3.8"

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n biotite-dev -c anaconda -c conda-forge python=%PY_VERSION% poetry
  - activate biotite-dev
  - poetry install

build: false

test_script:
  - pytest --ignore=tests//structure//test_trajectory.py --ignore=tests//application --ignore=tests//database

after_test:
  - poetry build

artifacts:
  - path: dist\*.whl
